import { MODULE_DISPLAY_NAME, MODULE_NAME, SOCKET_MODULE_NAME } from './constants';
import { 
  registerSettings, 
  LARGE_BUTTONS_SETTING,
  LARGE_DOORS_SETTING,
  CHARACTER_SHEET_SETTING, 
  PULL_FOCUS_KEYBIND, 
  PULL_FOCUS_PAN_SPEED, 
  PULL_FOCUS_PLAYER,
  LONG_TOUCH_TIMEOUT,
  LONG_TOUCH_TOGGLE,
  ZOOM_VALUE,
  BUTTON_SCALE_PX } from './settings';

export {
  MODULE_DISPLAY_NAME,
  MODULE_NAME,
  SOCKET_MODULE_NAME,
  LARGE_BUTTONS_SETTING,
  PULL_FOCUS_KEYBIND, 
  PULL_FOCUS_PAN_SPEED, 
  PULL_FOCUS_PLAYER,
  LARGE_DOORS_SETTING,
  CHARACTER_SHEET_SETTING,
  LONG_TOUCH_TIMEOUT,
  LONG_TOUCH_TOGGLE,
  ZOOM_VALUE,
  BUTTON_SCALE_PX,
  registerSettings
};

export default registerSettings;

